//! Content-defined chunking for large blobs
//! (spec/versioned-workspace-research-note.md §10.1 item 1; untie-substrate
//! readiness tracker Phase 1; completes DR-0033 Decision 4's tiering).
//!
//! Whole-blob granularity means a one-byte append to a large file mints a
//! whole new blob. Large blobs become FastCDC-style chunk lists whose
//! boundaries depend on content, not offsets, so storage and transfer
//! dedupe at chunk level and an edit re-mints only the chunk(s) it
//! touches. **The file's identity is the stable root hash** — manifests
//! and file-handle edges keep storing one hash exactly as today, and a
//! blob below the threshold keeps its plain content hash, so nothing
//! upstream re-keys. Erasure composes at chunk level with the retained
//! root as the honesty-downgrade handle (that policy lives upstream).
//!
//! Everything here is FROZEN IDENTITY once shipped: the gear table, the
//! normalization masks, and the size parameters all participate in chunk
//! boundaries, and the root derivation participates in file identity —
//! changing any of them re-keys every large blob. The chunk/root hash is
//! the house 64-bit FNV-1a content-id primitive (matching the content
//! store's blob ids); upgrading the hash family is a separate, explicit
//! re-keying decision, not a knob.
//!
//! Pure and host-agnostic — no store handle, no feature gate.

/// Chunking parameters. `whole_blob_threshold` keeps small files at plain
/// content-hash identity; min/avg/max bound FastCDC chunk sizes. The
/// defaults are identity-bearing for every blob chunked with them.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct ChunkingConfig {
    pub whole_blob_threshold: usize,
    pub min_size: usize,
    pub avg_size: usize,
    pub max_size: usize,
}

impl Default for ChunkingConfig {
    fn default() -> Self {
        Self {
            whole_blob_threshold: 256 * 1024,
            min_size: 64 * 1024,
            avg_size: 256 * 1024,
            max_size: 1024 * 1024,
        }
    }
}

/// One chunk of a large blob: its content id and its place in the file.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ChunkRef {
    pub hash: String,
    pub offset: usize,
    pub len: usize,
}

/// A chunked (or whole) blob. `root_hash` is the file's identity: for a
/// blob below the threshold it is the plain content hash (identical to
/// the un-chunked world); above it, the hash over the ordered child
/// chunk ids.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ChunkTree {
    pub root_hash: String,
    /// Empty for a whole blob (the root IS the content hash).
    pub chunks: Vec<ChunkRef>,
}

impl ChunkTree {
    pub fn is_whole_blob(&self) -> bool {
        self.chunks.is_empty()
    }
}

/// 64-bit FNV-1a over raw bytes — the byte-level twin of the store's
/// `stable_hash_hex` (identical constants, identical result for UTF-8
/// input), so chunk ids and blob ids share one id space.
pub fn content_hash_hex(bytes: &[u8]) -> String {
    let mut hash = 0xcbf29ce484222325u64;
    for byte in bytes {
        hash ^= u64::from(*byte);
        hash = hash.wrapping_mul(0x100000001b3);
    }
    format!("{hash:016x}")
}

/// The FastCDC gear table, generated by splitmix64 over the byte value —
/// deterministic, seedless at runtime, FROZEN (identity-bearing).
const fn splitmix64(seed: u64) -> u64 {
    let mut z = seed.wrapping_add(0x9e3779b97f4a7c15);
    z = (z ^ (z >> 30)).wrapping_mul(0xbf58476d1ce4e5b9);
    z = (z ^ (z >> 27)).wrapping_mul(0x94d049bb133111eb);
    z ^ (z >> 31)
}

const GEAR: [u64; 256] = {
    let mut table = [0u64; 256];
    let mut index = 0;
    while index < 256 {
        table[index] = splitmix64(index as u64);
        index += 1;
    }
    table
};

/// FastCDC normalization masks derived from the average size: harder
/// boundary condition (more mask bits) before the average point, easier
/// after — normalized chunking level 2.
fn masks(avg_size: usize) -> (u64, u64) {
    let bits = usize::BITS - (avg_size.max(2) - 1).leading_zeros();
    let hard = bits + 2;
    let easy = bits.saturating_sub(2).max(1);
    ((1u64 << hard.min(63)) - 1, (1u64 << easy.min(63)) - 1)
}

/// Content-defined chunk boundaries (FastCDC): every returned range is
/// within [min, max] except a short final remainder.
fn chunk_ranges(data: &[u8], config: &ChunkingConfig) -> Vec<(usize, usize)> {
    let (mask_hard, mask_easy) = masks(config.avg_size);
    let mut ranges = Vec::new();
    let mut start = 0usize;
    while start < data.len() {
        let remaining = data.len() - start;
        if remaining <= config.min_size {
            ranges.push((start, data.len()));
            break;
        }
        let end_cap = (start + config.max_size).min(data.len());
        let normal_point = (start + config.avg_size).min(end_cap);
        let mut fingerprint = 0u64;
        let mut cut = end_cap;
        let mut position = start;
        while position < end_cap {
            fingerprint = (fingerprint << 1).wrapping_add(GEAR[data[position] as usize]);
            if position - start + 1 >= config.min_size {
                let mask = if position < normal_point {
                    mask_hard
                } else {
                    mask_easy
                };
                if fingerprint & mask == 0 {
                    cut = position + 1;
                    break;
                }
            }
            position += 1;
        }
        ranges.push((start, cut));
        start = cut;
    }
    ranges
}

/// Chunk a blob. Below the threshold: whole-blob, root = plain content
/// hash, no chunk list. Above: FastCDC chunks; root = content hash over
/// the ordered child chunk ids (each id's 16 hex bytes, concatenated).
pub fn chunk_blob(data: &[u8], config: &ChunkingConfig) -> ChunkTree {
    if data.len() <= config.whole_blob_threshold {
        return ChunkTree {
            root_hash: content_hash_hex(data),
            chunks: Vec::new(),
        };
    }
    let mut chunks = Vec::new();
    let mut id_bytes: Vec<u8> = Vec::new();
    for (start, end) in chunk_ranges(data, config) {
        let hash = content_hash_hex(&data[start..end]);
        id_bytes.extend_from_slice(hash.as_bytes());
        chunks.push(ChunkRef {
            hash,
            offset: start,
            len: end - start,
        });
    }
    ChunkTree {
        root_hash: content_hash_hex(&id_bytes),
        chunks,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::BTreeSet;

    /// Small test parameters so fixtures stay kilobytes; the DEFAULTS are
    /// identity-bearing and exercised for shape only.
    fn test_config() -> ChunkingConfig {
        ChunkingConfig {
            whole_blob_threshold: 512,
            min_size: 128,
            avg_size: 512,
            max_size: 2048,
        }
    }

    /// Deterministic pseudo-random content (splitmix64 stream).
    fn data(len: usize, seed: u64) -> Vec<u8> {
        let mut bytes = Vec::with_capacity(len);
        let mut word = 0u64;
        for index in 0..len {
            if index % 8 == 0 {
                word = splitmix64(seed.wrapping_add((index / 8) as u64));
            }
            bytes.push((word >> ((index % 8) * 8)) as u8);
        }
        bytes
    }

    /// Below the threshold a blob keeps its plain content hash — nothing
    /// upstream re-keys when chunking ships.
    #[test]
    fn small_blobs_keep_plain_content_identity() {
        let blob = data(300, 1);
        let tree = chunk_blob(&blob, &test_config());
        assert!(tree.is_whole_blob());
        assert_eq!(tree.root_hash, content_hash_hex(&blob));
    }

    /// Chunking is deterministic, boundaries respect min/max, chunks tile
    /// the blob exactly, and the root is stable.
    #[test]
    fn chunking_is_deterministic_and_tiles_the_blob() {
        let blob = data(20_000, 2);
        let config = test_config();
        let tree_a = chunk_blob(&blob, &config);
        let tree_b = chunk_blob(&blob, &config);
        assert_eq!(tree_a, tree_b);
        assert!(tree_a.chunks.len() > 1, "large blob actually chunks");
        let mut cursor = 0usize;
        for chunk in &tree_a.chunks {
            assert_eq!(chunk.offset, cursor);
            assert!(chunk.len <= config.max_size);
            cursor += chunk.len;
        }
        assert_eq!(cursor, blob.len(), "chunks tile the blob");
        for chunk in &tree_a.chunks[..tree_a.chunks.len() - 1] {
            assert!(chunk.len >= config.min_size);
        }
    }

    /// The dedup payoff: a one-byte APPEND to a large blob re-mints only
    /// the tail — every other chunk id is shared with the original.
    #[test]
    fn append_shares_all_but_the_tail() {
        let blob = data(20_000, 3);
        let mut appended = blob.clone();
        appended.push(0xAB);
        let config = test_config();
        let before: Vec<String> = chunk_blob(&blob, &config)
            .chunks
            .into_iter()
            .map(|chunk| chunk.hash)
            .collect();
        let after: Vec<String> = chunk_blob(&appended, &config)
            .chunks
            .into_iter()
            .map(|chunk| chunk.hash)
            .collect();
        assert_eq!(
            before[..before.len() - 1],
            after[..before.len() - 1],
            "every chunk before the tail is byte-identical"
        );
        assert_ne!(before.last(), after.last(), "the tail re-mints");
    }

    /// A mid-file edit is contained: boundaries re-synchronize, so chunks
    /// far from the edit keep their ids (content-defined, not offset-
    /// defined — the property a fixed-size splitter lacks).
    #[test]
    fn mid_file_edit_is_contained() {
        let blob = data(40_000, 4);
        let mut edited = blob.clone();
        edited[20_000] ^= 0xFF;
        let config = test_config();
        let before: BTreeSet<String> = chunk_blob(&blob, &config)
            .chunks
            .into_iter()
            .map(|chunk| chunk.hash)
            .collect();
        let after: BTreeSet<String> = chunk_blob(&edited, &config)
            .chunks
            .into_iter()
            .map(|chunk| chunk.hash)
            .collect();
        let shared = before.intersection(&after).count();
        assert!(
            shared * 2 > before.len(),
            "most chunk ids survive a one-byte mid-file edit \
             (shared {shared} of {})",
            before.len()
        );
        let root_before = chunk_blob(&blob, &config).root_hash;
        let root_after = chunk_blob(&edited, &config).root_hash;
        assert_ne!(root_before, root_after, "identity still changes");
    }

    /// The default (identity-bearing) parameters chunk a multi-megabyte
    /// blob into bounded chunks.
    #[test]
    fn default_config_shape() {
        let blob = data(3 * 1024 * 1024, 5);
        let tree = chunk_blob(&blob, &ChunkingConfig::default());
        assert!(!tree.is_whole_blob());
        assert!(tree.chunks.len() >= 3);
        assert!(tree.chunks.iter().all(|chunk| chunk.len <= 1024 * 1024));
    }
}
