//! Generates the body parser's `EFFECT_OPERATION_GRAMMAR` table from the
//! canonical embedded std package manifests (`std/manifests/*.json`).
//!
//! The manifests are the single source of construct grammar (DR-0011,
//! spec/construct-grammar.md "Two-Shape Meta-Grammar", Option A): each
//! `effect_operation` construct carries a `grammar` object, and this script
//! transcribes it into the `EffectOperationSpec` rows `parse_effect_operation`
//! reads. The spec types themselves stay hand-written in `body.rs`; only the
//! table const is generated (into `$OUT_DIR/effect_operation_grammar.rs`).
//!
//! A malformed manifest fails the build with a message naming the manifest and
//! the problem — grammar drift is impossible by construction.

use std::{env, fs, path::PathBuf};

use serde_json::Value;

/// The embedded std manifests, relative to this crate's manifest dir. Keep in
/// sync with `EMBEDDED_STD_MANIFESTS` in crates/whipplescript-cli/src/main.rs.
const STD_MANIFESTS: &[&str] = &[
    "../../std/manifests/memory.json",
    "../../std/manifests/messaging.json",
];

/// The DR-0011 grammar vocabulary (mirrors whipplescript-core's
/// `CONSTRUCT_GRAMMAR_*` constants; a build script cannot depend on the crate
/// graph it builds for).
const CONNECTIVES: &[&str] = &["from", "for", "into", "to", "via"];
const SLOT_KINDS: &[&str] = &["identifier", "expression"];
const BINDING_MODES: &[&str] = &["required", "optional", "none"];

fn main() {
    let manifest_dir = PathBuf::from(
        env::var("CARGO_MANIFEST_DIR").expect("cargo always sets CARGO_MANIFEST_DIR"),
    );
    let out_dir = env::var("OUT_DIR").expect("cargo always sets OUT_DIR");

    let mut rows = String::new();
    let mut seen_keywords: Vec<(String, String)> = Vec::new();
    for relative in STD_MANIFESTS {
        let path = manifest_dir.join(relative);
        println!("cargo:rerun-if-changed={}", path.display());
        let label = path
            .file_name()
            .map(|name| name.to_string_lossy().into_owned())
            .unwrap_or_else(|| relative.to_string());
        let json = fs::read_to_string(&path).unwrap_or_else(|error| {
            panic!(
                "std manifest `{label}` could not be read from `{}`: {error}",
                path.display()
            )
        });
        let manifest: Value = serde_json::from_str(&json)
            .unwrap_or_else(|error| panic!("std manifest `{label}` is not valid JSON: {error}"));
        for library in manifest
            .get("libraries")
            .and_then(Value::as_array)
            .into_iter()
            .flatten()
        {
            for construct in library
                .get("constructs")
                .and_then(Value::as_array)
                .into_iter()
                .flatten()
            {
                emit_construct_row(&label, construct, &mut seen_keywords, &mut rows);
            }
        }
    }

    let generated = format!(
        "// Generated by build.rs from std/manifests/*.json — do not edit.\n\
         //\n\
         // The compiled-in table of `effect_operation` grammars (DR-0011): each row\n\
         // transcribes one embedded std manifest construct's `grammar` object. A\n\
         // leading rule-body keyword that matches an entry here is parsed by\n\
         // `parse_effect_operation`.\n\
         const EFFECT_OPERATION_GRAMMAR: &[EffectOperationSpec] = &[\n{rows}];\n"
    );
    let out_path = PathBuf::from(out_dir).join("effect_operation_grammar.rs");
    fs::write(&out_path, generated).unwrap_or_else(|error| {
        panic!(
            "could not write generated grammar table `{}`: {error}",
            out_path.display()
        )
    });
}

/// Validate one construct's `grammar` object and append its generated
/// `EffectOperationSpec` row. Mirrors the CLI manifest validation
/// (`package_construct_grammar`): shape/keyword/slot/connective/binding
/// vocabulary plus keyword and target_capability transcription.
fn emit_construct_row(
    label: &str,
    construct: &Value,
    seen_keywords: &mut Vec<(String, String)>,
    rows: &mut String,
) {
    let construct_id = construct
        .get("id")
        .and_then(Value::as_str)
        .unwrap_or("<missing id>");
    let fail = |problem: &str| -> ! {
        panic!("std manifest `{label}` construct `{construct_id}`: {problem}")
    };
    let family = construct
        .get("construct_family")
        .and_then(Value::as_str)
        .unwrap_or_else(|| fail("missing `construct_family`"));
    if family != "effect_operation" {
        fail(&format!(
            "unsupported construct_family `{family}`; embedded std constructs are `effect_operation`"
        ));
    }
    let construct_keyword = construct
        .get("keyword")
        .and_then(Value::as_str)
        .unwrap_or_else(|| fail("missing `keyword`"));
    let construct_target = construct
        .get("target_capability")
        .and_then(Value::as_str)
        .unwrap_or_else(|| fail("missing `target_capability`"));
    let grammar = construct.get("grammar").unwrap_or_else(|| {
        fail("missing `grammar` object (the manifests are the single source of parse grammar)")
    });

    let shape = grammar
        .get("shape")
        .and_then(Value::as_str)
        .unwrap_or_else(|| fail("grammar missing `shape`"));
    if shape == "declaration_block" {
        fail("grammar shape `declaration_block` is not yet supported in package manifests");
    }
    if shape != "effect_operation" {
        fail(&format!(
            "grammar uses unsupported shape `{shape}`; expected `effect_operation`"
        ));
    }
    let keyword = grammar
        .get("keyword")
        .and_then(Value::as_str)
        .unwrap_or_else(|| fail("grammar missing `keyword`"));
    if keyword != construct_keyword {
        fail(&format!(
            "grammar keyword `{keyword}` does not match the construct keyword `{construct_keyword}`"
        ));
    }
    if let Some((_, previous)) = seen_keywords
        .iter()
        .find(|(seen, _)| seen == construct_keyword)
    {
        fail(&format!(
            "keyword `{construct_keyword}` is already provided by `{previous}`; effect_operation keywords must be unique across the embedded std manifests"
        ));
    }
    seen_keywords.push((construct_keyword.to_owned(), label.to_owned()));

    let mut slot_rows = String::new();
    for slot in grammar
        .get("slots")
        .and_then(Value::as_array)
        .unwrap_or_else(|| fail("grammar missing `slots` array"))
    {
        let name = slot
            .get("name")
            .and_then(Value::as_str)
            .unwrap_or_else(|| fail("grammar slot missing `name`"));
        let kind = slot
            .get("kind")
            .and_then(Value::as_str)
            .unwrap_or_else(|| fail("grammar slot missing `kind`"));
        if !SLOT_KINDS.contains(&kind) {
            fail(&format!(
                "grammar slot `{name}` uses unsupported kind `{kind}`; expected one of {SLOT_KINDS:?}"
            ));
        }
        let connective = match slot.get("connective") {
            None | Some(Value::Null) => None,
            Some(connective) => {
                let connective = connective.as_str().unwrap_or_else(|| {
                    fail(&format!(
                        "grammar slot `{name}` connective must be a string"
                    ))
                });
                if !CONNECTIVES.contains(&connective) {
                    fail(&format!(
                        "grammar slot `{name}` uses unsupported connective `{connective}`; expected one of {CONNECTIVES:?}"
                    ));
                }
                Some(connective)
            }
        };
        let kind_variant = if kind == "identifier" {
            "SlotKind::Identifier"
        } else {
            "SlotKind::Expression"
        };
        let connective_expr = match connective {
            Some(connective) => format!("Some({connective:?})"),
            None => "None".to_owned(),
        };
        slot_rows.push_str(&format!(
            "            EffectSlotSpec {{\n\
             \x20               name: {name:?},\n\
             \x20               kind: {kind_variant},\n\
             \x20               connective: {connective_expr},\n\
             \x20           }},\n"
        ));
    }

    let payload_expr = match grammar.get("payload") {
        None | Some(Value::Null) => "None".to_owned(),
        Some(payload) => {
            let mut field_rows = String::new();
            for field in payload
                .get("fields")
                .and_then(Value::as_array)
                .unwrap_or_else(|| fail("grammar payload missing `fields` array"))
            {
                let name = field
                    .get("name")
                    .and_then(Value::as_str)
                    .unwrap_or_else(|| fail("grammar payload field missing `name`"));
                let kind = field
                    .get("kind")
                    .and_then(Value::as_str)
                    .unwrap_or_else(|| fail("grammar payload field missing `kind`"));
                if kind != "expression" {
                    fail(&format!(
                        "grammar payload field `{name}` uses unsupported kind `{kind}`; payload fields are `expression`"
                    ));
                }
                let required = field
                    .get("required")
                    .and_then(Value::as_bool)
                    .unwrap_or(true);
                field_rows.push_str(&format!(
                    "            PayloadFieldSpec {{\n\
                     \x20               name: {name:?},\n\
                     \x20               required: {required},\n\
                     \x20           }},\n"
                ));
            }
            format!("Some(&[\n{field_rows}        ])")
        }
    };

    let binding = grammar
        .get("binding")
        .and_then(Value::as_str)
        .unwrap_or_else(|| fail("grammar missing `binding`"));
    if !BINDING_MODES.contains(&binding) {
        fail(&format!(
            "grammar uses unsupported binding `{binding}`; expected one of {BINDING_MODES:?}"
        ));
    }
    let binding_variant = match binding {
        "required" => "BindingMode::Required",
        "optional" => "BindingMode::Optional",
        _ => "BindingMode::None",
    };

    let target_capability = grammar
        .get("target_capability")
        .and_then(Value::as_str)
        .unwrap_or_else(|| fail("grammar missing `target_capability`"));
    if target_capability != construct_target {
        fail(&format!(
            "grammar target_capability `{target_capability}` does not match the construct target_capability `{construct_target}`"
        ));
    }

    rows.push_str(&format!(
        "    EffectOperationSpec {{\n\
         \x20       keyword: {keyword:?},\n\
         \x20       slots: &[\n{slot_rows}        ],\n\
         \x20       payload: {payload_expr},\n\
         \x20       binding: {binding_variant},\n\
         \x20       target_capability: {target_capability:?},\n\
         \x20   }},\n"
    ));
}
