// The Cloudflare Worker + Durable Object shell for the WhippleScript runtime
// (DR-0033 chunk 5d). The Rust core is compiled to wasm and exposes
// `WasmDurableInstance` (create / step / status); this shell supplies the three
// pieces of JS glue the boundary needs and NOTHING ELSE -- no scheduling logic:
//
//   1. a `DoSqlBridge` over the object's SQLite (`state.storage.sql`),
//   2. the `fetch` for each `needs_http` round the core suspends on, and
//   3. JSON marshalling of the step protocol.
//
// The core is sans-IO: `step()` returns either a request to `fetch` (then call
// `step` again with the response) or a terminal. Because the in-flight effect is
// held inside the wasm instance AND the durable state lives in DO SQLite, an
// isolate eviction between rounds loses nothing -- a later request rehydrates.
//
// Aligns with Cloudflare docs: DO SQLite storage API (`ctx.storage.sql.exec`),
// positional-parameter binding, and `new_sqlite_classes` migrations (wrangler.toml).

// Generated by `wasm-pack build --target bundler` (see README). The build emits
// `pkg/whipplescript_host_do.js` + `.wasm` from the `#[wasm_bindgen]` surface.
import initSync, { WasmDurableInstance } from "../pkg/whipplescript_host_do";
// The wasm bytes, inlined by the bundler so the Worker is a single module.
import wasmModule from "../pkg/whipplescript_host_do_bg.wasm";

export interface Env {
  WORKFLOW_INSTANCE: DurableObjectNamespace;
  // Secrets injected as DO bindings -- the coerce/agent provider credentials the
  // sans-IO core asks for via `needs_http`. Wired into DurableEffectPorts in a
  // follow-on once the Rust `create` accepts them (see README "Effect creds").
  ANTHROPIC_API_KEY?: string;
  OPENAI_API_KEY?: string;
}

// Row objects from `sql.exec` are column-name keyed; the Rust `DoSql` contract
// wants each row as a positional array in SELECT order. Cloudflare preserves
// column order in the returned objects, so `Object.values` reconstructs it.
function rowsToPositionalJson(cursor: Iterable<Record<string, unknown>>): string {
  const rows: unknown[][] = [];
  for (const row of cursor) {
    rows.push(Object.values(row));
  }
  return JSON.stringify(rows);
}

// `state.storage.sql` as the `DoSqlBridge` the wasm core imports. Params arrive as
// a JSON array of `null | number | string` (the marshalled `SqlValue`s).
function makeBridge(sql: SqlStorage) {
  return {
    exec(query: string, paramsJson: string): number {
      const params = JSON.parse(paramsJson) as unknown[];
      const cursor = sql.exec(query, ...params);
      return cursor.rowsWritten;
    },
    query(query: string, paramsJson: string): string {
      const params = JSON.parse(paramsJson) as unknown[];
      const cursor = sql.exec(query, ...params);
      return rowsToPositionalJson(cursor);
    },
  };
}

let wasmReady = false;
async function ensureWasm(): Promise<void> {
  if (!wasmReady) {
    await initSync(wasmModule);
    wasmReady = true;
  }
}

type StepOutcome =
  | { kind: "needs_http"; request: { url: string; headers: [string, string][]; body: unknown } }
  | { kind: "terminal" }
  | { kind: "parked" }
  | { kind: "failed"; message: string };

// Perform one suspended HTTP round and marshal the result back for `step`.
async function performFetch(req: {
  url: string;
  headers: [string, string][];
  body: unknown;
}): Promise<string> {
  try {
    const resp = await fetch(req.url, {
      method: "POST",
      headers: Object.fromEntries(req.headers),
      body: JSON.stringify(req.body),
    });
    return JSON.stringify({ status: resp.status, body: await resp.json() });
  } catch (error) {
    // The core maps `{"error": ...}` to a TransportError terminal.
    return JSON.stringify({ error: error instanceof Error ? error.message : String(error) });
  }
}

export class WorkflowInstance implements DurableObject {
  constructor(
    private ctx: DurableObjectState,
    private env: Env,
  ) {}

  // POST /start { program, input, principal } -- create + drive to the first
  // suspension or terminal. Subsequent external events / alarms re-enter and drive
  // further; the durable state is entirely in DO SQLite.
  async fetch(request: Request): Promise<Response> {
    await ensureWasm();
    const { program, input, principal } = (await request.json()) as {
      program: string;
      input: string;
      principal: string;
    };

    const bridge = makeBridge(this.ctx.storage.sql);
    // Provider creds from DO secrets (optional; store-only workflows omit both).
    // Same JSON shape for coerce and agent turns; a live agent turn with tools
    // also needs a tool-executor sidecar (the remaining async-tool seam).
    const anthropicConfig = (model: string, maxTokens: number) =>
      this.env.ANTHROPIC_API_KEY
        ? JSON.stringify({
            provider: "anthropic",
            base_url: "https://api.anthropic.com",
            api_key: this.env.ANTHROPIC_API_KEY,
            model,
            max_tokens: maxTokens,
          })
        : undefined;
    const coerceConfig = anthropicConfig("claude-3-5-sonnet-latest", 1024);
    const agentConfig = anthropicConfig("claude-3-5-sonnet-latest", 4096);
    const instance = WasmDurableInstance.create(
      bridge,
      program,
      input ?? "{}",
      principal ?? "local/Workflow",
      coerceConfig,
      agentConfig,
    );

    // The sans-IO loop: step -> maybe fetch -> step, until a terminal. Each `fetch`
    // is one provider round; the core parses the response and continues (or, on the
    // final round, settles). A production shell persists after each round so the
    // object can hibernate; here we run the loop within one request for clarity.
    let responseJson: string | undefined = undefined;
    for (;;) {
      const outcome = JSON.parse(instance.step(responseJson)) as StepOutcome;
      if (outcome.kind !== "needs_http") {
        return Response.json({ status: instance.status(), outcome: outcome.kind });
      }
      responseJson = await performFetch(outcome.request);
    }
  }
}

// The Worker entrypoint routes to the addressed instance object.
export default {
  async fetch(request: Request, env: Env, _ctx: ExecutionContext): Promise<Response> {
    const url = new URL(request.url);
    const id = url.searchParams.get("id") ?? "default";
    const stub = env.WORKFLOW_INSTANCE.get(env.WORKFLOW_INSTANCE.idFromName(id));
    return stub.fetch(request);
  },
} satisfies ExportedHandler<Env>;
