// The Cloudflare Worker + Durable Object shell for the WhippleScript runtime
// (DR-0033 chunk 5d). The Rust core is compiled to wasm and exposes
// `WasmDurableInstance` (create / step / status); this shell supplies the three
// pieces of JS glue the boundary needs and NOTHING ELSE -- no scheduling logic:
//
//   1. a `DoSqlBridge` over the object's SQLite (`state.storage.sql`),
//   2. the `fetch` for each `needs_http` round the core suspends on, and
//   3. JSON marshalling of the step protocol.
//
// The core is sans-IO: `step()` returns either a request to `fetch` (then call
// `step` again with the response) or a terminal. Because the in-flight effect is
// held inside the wasm instance AND the durable state lives in DO SQLite, an
// isolate eviction between rounds loses nothing -- a later request rehydrates.
//
// Aligns with Cloudflare docs: DO SQLite storage API (`ctx.storage.sql.exec`),
// positional-parameter binding, and `new_sqlite_classes` migrations (wrangler.toml).

// Generated by `wasm-bindgen --target bundler` (see README). Workers differ
// from webpack-style bundlers: importing a `.wasm` yields a WebAssembly.Module
// (NOT an instantiated exports object), so the pkg's self-initializing entry
// module cannot run under workerd. We bypass it and instantiate here: the
// module's single import namespace is the generated `_bg.js` glue itself.
import wasmModule from "../pkg/whipplescript_host_do_bg.wasm";
import * as bindings from "../pkg/whipplescript_host_do_bg.js";
import { WasmDurableInstance, __wbg_set_wasm } from "../pkg/whipplescript_host_do_bg.js";
import { Container, getRandom } from "@cloudflare/containers";

const wasmInstance = new WebAssembly.Instance(wasmModule, {
  "./whipplescript_host_do_bg.js": bindings,
});
__wbg_set_wasm(wasmInstance.exports);
(wasmInstance.exports as { __wbindgen_start?: () => void }).__wbindgen_start?.();

export interface Env {
  WORKFLOW_INSTANCE: DurableObjectNamespace;
  // Secrets injected as DO bindings -- the coerce/agent provider credentials the
  // sans-IO core asks for via `needs_http`. Wired into DurableEffectPorts in a
  // follow-on once the Rust `create` accepts them (see README "Effect creds").
  ANTHROPIC_API_KEY?: string;
  OPENAI_API_KEY?: string;
  // Dev/test override for the provider endpoint (e.g. a local mock in
  // `wrangler dev`); production omits it and uses the real Anthropic API.
  WHIP_PROVIDER_BASE_URL?: string;
  // Class-A executor sidecar (compute plane P8): where exec.command effects
  // go as whip-executor/1 HTTP rounds. Unset = exec effects error. URLs on
  // this host are routed to the EXECUTOR container pool, not the network.
  WHIP_EXECUTOR_URL?: string;
  // Environment component of the delta-kernel content key: the executor
  // image identity (image digest = environment hash, §5 of the compute-plane
  // note). `whip deploy` computes it from the Dockerfile + whip binary and
  // injects it, so a toolchain bump is a visible warm-start epoch that rolls
  // the cache. Unset = the "do-v0" default epoch.
  WHIP_COMPUTE_ENV_HASH?: string;
  EXECUTOR: DurableObjectNamespace<ExecutorContainer>;
}

// One Class-A executor instance (compute plane P8): a container running
// `whip executor` (whip-executor/1), paired 1:1 with this controlling DO.
// Stateless by design — hermeticity is demanded and audited, which is what
// makes the pool shareable. Egress default-deny is the container posture:
// the executor only ever answers this worker's in-cluster fetches.
export class ExecutorContainer extends Container {
  defaultPort = 8080;
  sleepAfter = "10m";
}

// Fixed pool size until platform autoscaling ships (manual knob, working
// zero-config default). `getRandom` is location-blind today — accepted.
const EXECUTOR_POOL_SIZE = 4;

// The DO schema (33 tables) as a bundled text module (wrangler.toml `rules`).
import DO_SCHEMA from "../do_schema.sql";

// Builtin capability seeds, mirroring the native migration-0001 builtin rows
// for the two effect families the DO drives today (schema.coerce + agent.tell).
// Applied once with the schema; program-specific registration happens through
// the normal registry path on create().
const BUILTIN_SEEDS = [
  `INSERT INTO capability_schemas (capability, description, schema_json) VALUES ('schema.coerce', 'Coerce unstructured data into a typed value.', '{}')`,
  `INSERT INTO effect_providers (provider_id, effect_kind, provider, capability, config_json) VALUES ('provider_coerce_builtin', 'schema.coerce', 'builtin-coerce', 'schema.coerce', '{}')`,
  `INSERT INTO capability_bindings (binding_id, program_id, capability, provider, config_json) VALUES ('binding_coerce_builtin', NULL, 'schema.coerce', 'builtin-coerce', '{}')`,
  `INSERT INTO capability_schemas (capability, description, schema_json) VALUES ('agent.tell', 'Run an agent turn.', '{}')`,
  `INSERT INTO effect_providers (provider_id, effect_kind, provider, capability, config_json) VALUES ('provider_agent_tell_builtin', 'agent.tell', 'builtin-agent-harness', 'agent.tell', '{}')`,
  `INSERT INTO capability_bindings (binding_id, program_id, capability, provider, config_json) VALUES ('binding_agent_tell_builtin', NULL, 'agent.tell', 'builtin-agent-harness', '{}')`,
  `INSERT INTO profiles (profile_id, name, description, enforcement_mode, allowed_capabilities, config_json) VALUES ('profile_repo_reader', 'repo-reader', 'Allow repository reads and agent turns without writes.', 'enforce', '["agent.tell","repo.read","human.ask","schema.coerce","event.emit","workflow.invoke"]', '{}')`,
];

// Idempotent first-touch bootstrap: a fresh DO has an empty SQLite; apply the
// schema + builtin seeds exactly once (schema_migrations doubles as the marker).
function ensureSchema(sql: SqlStorage): void {
  const marker = sql
    .exec(`SELECT name FROM sqlite_master WHERE type = 'table' AND name = 'schema_migrations'`)
    .toArray();
  if (marker.length > 0) {
    return;
  }
  sql.exec(DO_SCHEMA);
  for (const seed of BUILTIN_SEEDS) {
    sql.exec(seed);
  }
}

// Row objects from `sql.exec` are column-name keyed; the Rust `DoSql` contract
// wants each row as a positional array in SELECT order. Cloudflare preserves
// column order in the returned objects, so `Object.values` reconstructs it.
function rowsToPositionalJson(cursor: Iterable<Record<string, unknown>>): string {
  const rows: unknown[][] = [];
  for (const row of cursor) {
    rows.push(Object.values(row));
  }
  return JSON.stringify(rows);
}

// `state.storage.sql` as the `DoSqlBridge` the wasm core imports. Params arrive as
// a JSON array of `null | number | string` (the marshalled `SqlValue`s).
function makeBridge(sql: SqlStorage) {
  return {
    exec(query: string, paramsJson: string): number {
      const params = JSON.parse(paramsJson) as unknown[];
      const cursor = sql.exec(query, ...params);
      return cursor.rowsWritten;
    },
    query(query: string, paramsJson: string): string {
      const params = JSON.parse(paramsJson) as unknown[];
      const cursor = sql.exec(query, ...params);
      return rowsToPositionalJson(cursor);
    },
  };
}

type StepOutcome =
  | { kind: "needs_http"; request: { url: string; headers: [string, string][]; body: unknown } }
  | { kind: "terminal" }
  | { kind: "parked"; next_due_unix_ms: number | null }
  | { kind: "failed"; message: string };

// Perform one suspended HTTP round and marshal the result back for `step`.
// Requests targeting the executor sentinel host are routed to a
// getRandom-picked container in the EXECUTOR pool instead of the network.
async function performFetch(
  req: {
    url: string;
    headers: [string, string][];
    body: unknown;
  },
  env?: Env,
): Promise<string> {
  try {
    const init = {
      method: "POST",
      headers: Object.fromEntries(req.headers),
      body: JSON.stringify(req.body),
    };
    const executorHost = env?.WHIP_EXECUTOR_URL;
    const resp =
      executorHost && req.url.startsWith(executorHost)
        ? await (await getRandom(env.EXECUTOR, EXECUTOR_POOL_SIZE)).fetch(req.url, init)
        : await fetch(req.url, init);
    return JSON.stringify({ status: resp.status, body: await resp.json() });
  } catch (error) {
    // The core maps `{"error": ...}` to a TransportError terminal.
    return JSON.stringify({ error: error instanceof Error ? error.message : String(error) });
  }
}

interface Bootstrap {
  program: string;
  input: string;
  principal: string;
  // Deploy-shipped AGENTS.md/CLAUDE.md content (context-assembly Phase 3):
  // [{ path, content }] in injection order; resolved from the DO store by the
  // agent turn (the DO has no filesystem).
  project_context?: { path: string; content: string }[];
  // Deploy-shipped script capabilities (compute plane P8): the DO-store
  // mirror of the native script manifest. Each body is verified against its
  // sha256 pin at registration; argv carries the "{script}" placeholder.
  scripts?: {
    name: string;
    argv: string[];
    sha256: string;
    env?: Record<string, string>;
    hermetic?: boolean;
    body: string;
  }[];
}

export class WorkflowInstance implements DurableObject {
  constructor(
    private ctx: DurableObjectState,
    private env: Env,
  ) {}

  // POST /start { program, input, principal } -- create + drive to the first
  // suspension or terminal. Subsequent external events / alarms re-enter and drive
  // further; the durable state is entirely in DO SQLite.
  async fetch(request: Request): Promise<Response> {
    const { program, input, principal, project_context, scripts } =
      (await request.json()) as Partial<Bootstrap>;
    let bootstrap: Bootstrap | undefined;
    if (program) {
      bootstrap = {
        program,
        input: input ?? "{}",
        principal: principal ?? "local/Workflow",
        project_context,
        scripts,
      };
      // Persisted so an alarm (or a body-less poke) can rehydrate the wasm
      // instance without the caller resupplying the program.
      await this.ctx.storage.put("bootstrap", bootstrap);
    } else {
      bootstrap = await this.ctx.storage.get<Bootstrap>("bootstrap");
    }
    if (!bootstrap) {
      return Response.json({ error: "no program: POST { program, input, principal } first" }, { status: 400 });
    }
    const result = await this.drive(bootstrap);
    return Response.json(result);
  }

  // The DO's single wake-up (DR-0033 Phase 6): a parked instance with pending
  // timers/deadlines scheduled this; re-enter and drive — the due-time pass
  // fires the timers, the rule pass sees the facts, and the run continues.
  async alarm(): Promise<void> {
    const bootstrap = await this.ctx.storage.get<Bootstrap>("bootstrap");
    if (bootstrap) {
      const result = await this.drive(bootstrap);
      console.log(`alarm fired: drove instance to ${result.status} (${result.outcome})`);
    }
  }

  private async drive(bootstrap: Bootstrap): Promise<{ status: string; outcome: string }> {
    ensureSchema(this.ctx.storage.sql);
    const bridge = makeBridge(this.ctx.storage.sql);
    // Provider creds from DO secrets (optional; store-only workflows omit both).
    // Same JSON shape for coerce and agent turns; a live agent turn with tools
    // also needs a tool-executor sidecar (the remaining async-tool seam).
    const anthropicConfig = (model: string, maxTokens: number) =>
      this.env.ANTHROPIC_API_KEY
        ? JSON.stringify({
            provider: "anthropic",
            base_url: this.env.WHIP_PROVIDER_BASE_URL ?? "https://api.anthropic.com",
            api_key: this.env.ANTHROPIC_API_KEY,
            model,
            max_tokens: maxTokens,
          })
        : undefined;
    const coerceConfig = anthropicConfig("claude-3-5-sonnet-latest", 1024);
    const agentConfig = anthropicConfig("claude-3-5-sonnet-latest", 4096);
    // Class-A exec sidecar wiring (compute plane P8): the executor URL comes
    // from the environment; script env references resolve against DO secrets.
    const execConfig = this.env.WHIP_EXECUTOR_URL
      ? JSON.stringify({
          base_url: this.env.WHIP_EXECUTOR_URL,
          environment_epoch: this.env.WHIP_COMPUTE_ENV_HASH,
          env: {
            ...(this.env.ANTHROPIC_API_KEY ? { ANTHROPIC_API_KEY: this.env.ANTHROPIC_API_KEY } : {}),
            ...(this.env.OPENAI_API_KEY ? { OPENAI_API_KEY: this.env.OPENAI_API_KEY } : {}),
          },
        })
      : undefined;
    const instance = WasmDurableInstance.create(
      bridge,
      bootstrap.program,
      bootstrap.input,
      bootstrap.principal,
      coerceConfig,
      agentConfig,
      bootstrap.project_context ? JSON.stringify(bootstrap.project_context) : undefined,
      execConfig,
      bootstrap.scripts ? JSON.stringify(bootstrap.scripts) : undefined,
    );

    // The sans-IO loop: step -> maybe fetch -> step, until a terminal or a park.
    // Each `fetch` is one provider round; the core parses the response and
    // continues (or, on the final round, settles). A production shell persists
    // after each round so the object can hibernate; here we run the loop within
    // one request for clarity.
    let responseJson: string | undefined = undefined;
    for (;;) {
      const outcome = JSON.parse(instance.step(responseJson, Date.now())) as StepOutcome;
      if (outcome.kind === "needs_http") {
        responseJson = await performFetch(outcome.request, this.env);
        continue;
      }
      if (outcome.kind === "parked" && outcome.next_due_unix_ms != null) {
        // The instance holds pending timers/deadlines: schedule the DO's
        // single alarm at the earliest one (the Alarms seam, live).
        await this.ctx.storage.setAlarm(outcome.next_due_unix_ms);
      }
      return { status: instance.status(), outcome: outcome.kind };
    }
  }
}

// The Worker entrypoint routes to the addressed instance object.
export default {
  async fetch(request: Request, env: Env, _ctx: ExecutionContext): Promise<Response> {
    const url = new URL(request.url);
    const id = url.searchParams.get("id") ?? "default";
    const stub = env.WORKFLOW_INSTANCE.get(env.WORKFLOW_INSTANCE.idFromName(id));
    return stub.fetch(request);
  },
} satisfies ExportedHandler<Env>;
